#!/bin/bash

#set program name
PROGNAME="$(basename $0)"
function usage(){
    cat << EOS >&2
usage: $PROGNAME [-h, --help] [-s, --stop]

Optins:
  -h, --help    Show usage
  -s, --stop    stop hackmad
EOS
    exit 1
}


# オプションをパース
for opt in "$@"; do
    case "${opt}" in
        '-h'|'--help' )
            usage
        ;;
        '-s'|'--stop' )
            docker stop docker-hackmd_app_1 docker-hackmd_database_1
            shift
            exit 0
        ;;
        -* )
            echo "${PROGNAME}: illegal option --'$(echo $1 | sed 'S/^-*//' )'" 1>&2
            exit 1
        ;;
    esac
done


cd /Users/wistre/Workspace/docker-hackmd
END_TIME=$(($(date +%s) + 300))
(while [ $(date +%s) -lt $END_TIME ]
do 
    if grep "HTTP Server listening at port 3000" wilog.txt >/dev/null; then 
        echo "================================="
        echo "HTTP Server listening at port 3000"
        echo "=================================="
        break
    else
        sleep 1
    fi
done
open http://localhost:3000)&
docker-compose up |tee  wilog.txt 
